/**
 * @file docentesMock.ts
 * @description Dados simulados estritamente tipados para o catálogo de professores da instituição e seus vínculos com disciplinas.
 */

import type { Docente, DocenteDisciplinaVinculo } from './types';

export const DOCENTES_MOCK: Docente[] = [
  {
    id: '1',
    nome: 'Dr. Alan Turing Silva',
    titulacao: 'Doutorado',
    centroLotacao: 'CCEN - Centro de Ciências Exatas e da Natureza',
    unidadeVinculoId: '1',
    unidadeVinculoNome: 'Unidade Rio Branco - Campus Universitário',
    cursosVinculados: ['1', '3'],
    cargo: 'Professor Adjunto',
    jornada: 'DE - Dedicação Exclusiva',
    tempoCasa: 12,
    email: 'alan.turing@ufac.br',
  },
  {
    id: '2',
    nome: 'Dra. Ada Lovelace Souza',
    titulacao: 'Pós-Doutorado',
    centroLotacao: 'CCEN - Centro de Ciências Exatas e da Natureza',
    unidadeVinculoId: '1',
    unidadeVinculoNome: 'Unidade Rio Branco - Campus Universitário',
    cursosVinculados: ['1', '2', '5'],
    cargo: 'Professor Titular',
    jornada: 'DE - Dedicação Exclusiva',
    tempoCasa: 18,
    email: 'ada.lovelace@ufac.br',
  },
  {
    id: '3',
    nome: 'Me. Linus Torvalds Lima',
    titulacao: 'Mestrado',
    centroLotacao: 'CCEN - Centro de Ciências Exatas e da Natureza',
    unidadeVinculoId: '1',
    unidadeVinculoNome: 'Unidade Rio Branco - Campus Universitário',
    cursosVinculados: ['1', '2'],
    cargo: 'Professor Assistente',
    jornada: '40h',
    tempoCasa: 6,
    email: 'linus.torvalds@ufac.br',
  },
  {
    id: '4',
    nome: 'Dra. Grace Hopper Mendes',
    titulacao: 'Doutorado',
    centroLotacao: 'CCEN - Centro de Ciências Exatas e da Natureza',
    unidadeVinculoId: '1',
    unidadeVinculoNome: 'Unidade Rio Branco - Campus Universitário',
    cursosVinculados: ['1', '2', '4'],
    cargo: 'Professor Adjunto',
    jornada: 'DE - Dedicação Exclusiva',
    tempoCasa: 9,
    email: 'grace.hopper@ufac.br',
  },
  {
    id: '5',
    nome: 'Me. Donald Knuth Pereira',
    titulacao: 'Mestrado',
    centroLotacao: 'CCEN - Centro de Ciências Exatas e da Natureza',
    unidadeVinculoId: '1',
    unidadeVinculoNome: 'Unidade Rio Branco - Campus Universitário',
    cursosVinculados: ['3'],
    cargo: 'Professor Assistente',
    jornada: '40h',
    tempoCasa: 15,
    email: 'donald.knuth@ufac.br',
  },
  {
    id: '6',
    nome: 'Esp. Margaret Hamilton Costa',
    titulacao: 'Especialização',
    centroLotacao: 'CFCH - Centro de Filosofia e Ciências Humanas',
    unidadeVinculoId: '1',
    unidadeVinculoNome: 'Unidade Rio Branco - Campus Universitário',
    cursosVinculados: ['2', '6'],
    cargo: 'Professor do Magistério Superior',
    jornada: '20h',
    tempoCasa: 4,
    email: 'margaret.hamilton@ufac.br',
  },
];

export const DOCENTE_DISCIPLINAS_MOCK: DocenteDisciplinaVinculo[] = [
  // Dr. Alan Turing (Docente 1)
  {
    id: '101',
    docenteId: '1',
    docenteNome: 'Dr. Alan Turing Silva',
    disciplinaId: '1',
    disciplinaNome: 'Algoritmos e Estrutura de Dados I',
    codigoDisciplina: 'BSI101',
    cursoId: '1',
    cursoNome: 'Bacharelado em Sistemas de Informação',
    ano: 2026,
    semestre: 1,
  },
  {
    id: '102',
    docenteId: '1',
    docenteNome: 'Dr. Alan Turing Silva',
    disciplinaId: '8',
    disciplinaNome: 'Algoritmos Avançados e Grafos',
    codigoDisciplina: 'CCO102',
    cursoId: '3',
    cursoNome: 'Ciência da Computação',
    ano: 2026,
    semestre: 1,
  },
  // Dra. Ada Lovelace (Docente 2)
  {
    id: '103',
    docenteId: '2',
    docenteNome: 'Dra. Ada Lovelace Souza',
    disciplinaId: '2',
    disciplinaNome: 'Banco de Dados Avançado',
    codigoDisciplina: 'BSI204',
    cursoId: '1',
    cursoNome: 'Bacharelado em Sistemas de Informação',
    ano: 2026,
    semestre: 1,
  },
  {
    id: '104',
    docenteId: '2',
    docenteNome: 'Dra. Ada Lovelace Souza',
    disciplinaId: '5',
    disciplinaNome: 'Modelagem e Arquitetura de Software',
    codigoDisciplina: 'ESOFT301',
    cursoId: '2',
    cursoNome: 'Engenharia de Software',
    ano: 2026,
    semestre: 1,
  },
  // Me. Linus Torvalds (Docente 3)
  {
    id: '105',
    docenteId: '3',
    docenteNome: 'Me. Linus Torvalds Lima',
    disciplinaId: '3',
    disciplinaNome: 'Sistemas Operacionais e Redes',
    codigoDisciplina: 'BSI302',
    cursoId: '1',
    cursoNome: 'Bacharelado em Sistemas de Informação',
    ano: 2026,
    semestre: 1,
  },
  {
    id: '106',
    docenteId: '3',
    docenteNome: 'Me. Linus Torvalds Lima',
    disciplinaId: '6',
    disciplinaNome: 'DevOps e Infraestrutura em Nuvem',
    codigoDisciplina: 'ESOFT402',
    cursoId: '2',
    cursoNome: 'Engenharia de Software',
    ano: 2026,
    semestre: 1,
  },
  // Dra. Grace Hopper (Docente 4)
  {
    id: '107',
    docenteId: '4',
    docenteNome: 'Dra. Grace Hopper Mendes',
    disciplinaId: '4',
    disciplinaNome: 'Inteligência Artificial Aplicada',
    codigoDisciplina: 'BSI405',
    cursoId: '1',
    cursoNome: 'Bacharelado em Sistemas de Informação',
    ano: 2026,
    semestre: 1,
  },
  {
    id: '108',
    docenteId: '4',
    docenteNome: 'Dra. Grace Hopper Mendes',
    disciplinaId: '7',
    disciplinaNome: 'Qualidade e Testes de Software',
    codigoDisciplina: 'ESOFT205',
    cursoId: '2',
    cursoNome: 'Engenharia de Software',
    ano: 2026,
    semestre: 1,
  },
];
