# Generated by Django 6.0.2 on 2026-06-26 23:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_curso', models.CharField(max_length=20, unique=True)),
                ('nome_curso', models.CharField(max_length=255)),
                ('nivel_curso', models.CharField(choices=[('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação')], max_length=20)),
                ('turno_curso', models.CharField(blank=True, choices=[('Integral', 'Integral'), ('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Diurno', 'Diurno')], max_length=20, null=True)),
                ('modalidade_curso', models.CharField(blank=True, max_length=45, null=True)),
                ('area_conhecimento_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionamento_curso', models.CharField(choices=[('Em atividade', 'Em atividade'), ('Inativo', 'Inativo'), ('Suspenso', 'Suspenso')], default='Em atividade', max_length=20)),
                ('grau_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('ato_autorizacao_curso', models.TextField(blank=True, null=True)),
                ('ato_reconhecimento_curso', models.TextField(blank=True, null=True)),
                ('conceito_mec_curso', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf_usuario', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id_curriculo', models.AutoField(primary_key=True, serialize=False)),
                ('versao', models.CharField(max_length=50)),
                ('ano_inicio', models.IntegerField()),
                ('semestre_inicio', models.IntegerField()),
                ('regime_letivo', models.CharField(choices=[('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Semestral', max_length=20)),
                ('num_periodos_ideal', models.IntegerField(blank=True, null=True)),
                ('total_creditos', models.IntegerField(blank=True, null=True)),
                ('carga_horaria_total', models.IntegerField(blank=True, null=True)),
                ('carga_horaria_min_periodo', models.IntegerField(default=30)),
                ('carga_horaria_max_periodo', models.IntegerField(default=600)),
                ('num_trancamentos_totais', models.IntegerField(default=3)),
                ('num_trancamentos_parciais', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('Corrente', 'Corrente'), ('Ativa Anterior', 'Ativa Anterior'), ('Inativo', 'Inativo')], default='Ativa Anterior', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculos', to='base_ementario.curso')),
            ],
            options={
                'db_table': 'curriculo',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_disciplina', models.CharField(max_length=30, unique=True)),
                ('nome_disciplina', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('nota_minima_aprovacao', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('programa', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('avaliacao', models.TextField(blank=True, null=True)),
                ('bibliografia_basica', models.TextField(blank=True, null=True)),
                ('bibliografia_complementar', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cursos_vinculados', models.ManyToManyField(blank=True, related_name='disciplinas_diretas', to='base_ementario.curso')),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='CurriculoDisciplina',
            fields=[
                ('id_curriculo_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.IntegerField()),
                ('tipo_disciplina', models.CharField(choices=[('Obrigatória', 'Obrigatória'), ('Optativa', 'Optativa'), ('Eletiva', 'Eletiva')], default='Obrigatória', max_length=20)),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_ementario.curriculo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_ementario.disciplina')),
            ],
            options={
                'db_table': 'curriculo_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_docente', models.CharField(max_length=255)),
                ('titulacao_docente', models.CharField(blank=True, choices=[('Graduação', 'Graduação'), ('Especialização', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-Doutorado', 'Pós-Doutorado')], max_length=50, null=True)),
                ('centro_lotacao', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_docente', models.CharField(blank=True, choices=[('Professor Adjunto', 'Professor Adjunto'), ('Professor Assistente', 'Professor Assistente'), ('Professor Titular', 'Professor Titular'), ('Professor Substituto', 'Professor Substituto'), ('Professor do Magistério Superior', 'Professor do Magistério Superior')], max_length=100, null=True)),
                ('jornada_docente', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo_casa_docente', models.IntegerField(blank=True, null=True)),
                ('email_docente', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cursos_vinculados', models.ManyToManyField(blank=True, related_name='corpo_docente', to='base_ementario.curso')),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(blank=True, db_column='coordenador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_ementario.docente'),
        ),
        migrations.CreateModel(
            name='DocenteDisciplina',
            fields=[
                ('id_docente_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_disciplinas', to='base_ementario.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_docentes', to='base_ementario.disciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_disciplinas', to='base_ementario.docente')),
            ],
            options={
                'db_table': 'docente_disciplina',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCurso',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_documento', models.CharField(choices=[('Regulamento', 'Regulamento'), ('Portaria', 'Portaria'), ('Resolução', 'Resolução'), ('Outro', 'Outro')], default='Outro', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_ementario.curso')),
            ],
            options={
                'db_table': 'documento_curso',
            },
        ),
        migrations.CreateModel(
            name='PPC',
            fields=[
                ('id_ppc', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('arquivo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_ementario.curriculo')),
            ],
            options={
                'db_table': 'ppc',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id_unidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_unidade', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unidade',
                'indexes': [models.Index(fields=['sigla'], name='idx_sigla_unidade')],
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='unidade_vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes_vinculados', to='base_ementario.unidade'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_ementario.unidade'),
        ),
        migrations.CreateModel(
            name='CursoEdicaoUsuario',
            fields=[
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='edicao_usuario', serialize=False, to='base_ementario.curso')),
                ('nome_curso', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_curso', models.CharField(blank=True, choices=[('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação')], max_length=20, null=True)),
                ('turno_curso', models.CharField(blank=True, choices=[('Integral', 'Integral'), ('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Diurno', 'Diurno')], max_length=20, null=True)),
                ('modalidade_curso', models.CharField(blank=True, max_length=45, null=True)),
                ('area_conhecimento_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionamento_curso', models.CharField(blank=True, choices=[('Em atividade', 'Em atividade'), ('Inativo', 'Inativo'), ('Suspenso', 'Suspenso')], max_length=20, null=True)),
                ('grau_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('ato_autorizacao_curso', models.TextField(blank=True, null=True)),
                ('ato_reconhecimento_curso', models.TextField(blank=True, null=True)),
                ('conceito_mec_curso', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'curso_edicao_usuario',
            },
        ),
        migrations.AddIndex(
            model_name='curriculo',
            index=models.Index(fields=['status'], name='idx_status_curriculo'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculo',
            unique_together={('curso', 'versao', 'ano_inicio', 'semestre_inicio')},
        ),
        migrations.AddIndex(
            model_name='curriculodisciplina',
            index=models.Index(fields=['periodo'], name='idx_periodo_cd'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculodisciplina',
            unique_together={('curriculo', 'disciplina')},
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['codigo_curso'], name='idx_codigo_curso'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['nome_curso'], name='idx_nome_curso'),
        ),
        migrations.AddIndex(
            model_name='docentedisciplina',
            index=models.Index(fields=['ano', 'semestre'], name='idx_ano_semestre_dd'),
        ),
        migrations.AddIndex(
            model_name='docente',
            index=models.Index(fields=['nome_docente'], name='idx_nome_docente'),
        ),
        migrations.AddIndex(
            model_name='disciplina',
            index=models.Index(fields=['codigo_disciplina'], name='idx_codigo_disciplina'),
        ),
        migrations.AddIndex(
            model_name='disciplina',
            index=models.Index(fields=['nome_disciplina'], name='idx_nome_disciplina'),
        ),
    ]
