# Generated by Django 6.0.2 on 2026-07-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_ementario', '0004_expandir_curriculo_versao_codigo_disciplina'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='docente',
            name='email_docente',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='editado_manualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='inserido_manualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='ano_inicio',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='semestre_inicio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='curriculodisciplina',
            name='periodo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='curriculodisciplina',
            name='tipo_disciplina',
            field=models.CharField(choices=[('Obrigatória', 'Obrigatória'), ('Optativa', 'Optativa'), ('Eletiva', 'Eletiva'), ('Atividades Complementares de PG', 'Atividades Complementares de PG')], default='Obrigatória', max_length=50),
        ),
        migrations.AlterField(
            model_name='docentedisciplina',
            name='ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='docentedisciplina',
            name='semestre',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='curriculo',
            unique_together={('curso', 'versao', 'ano_inicio', 'semestre_inicio')},
        ),
    ]
