# Generated by Django 6.0.2 on 2026-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_ementario', '0005_alter_curriculo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cargo_docente',
            field=models.CharField(blank=True, choices=[('Professor Adjunto', 'Professor Adjunto'), ('Professor Assistente', 'Professor Assistente'), ('Professor Titular', 'Professor Titular'), ('Professor Substituto', 'Professor Substituto'), ('Professor Substituto do Magistério Superior', 'Professor Substituto do Magistério Superior'), ('Professor do Magistério Superior', 'Professor do Magistério Superior'), ('Professor do Magistério do EBTT', 'Professor do Magistério do EBTT'), ('PROFESSOR 3 GRAU - CONVÊNIO', 'PROFESSOR 3 GRAU - CONVÊNIO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docentedisciplina',
            name='ano',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(db_column='id_usuario', primary_key=True, serialize=False),
        ),
    ]
