/**
 * @file cursosMock.ts
 * @description Mock estático de dados tipados para simulação de retornos da API de Cursos.
 */

import type { Curso } from './types';

export const CURSOS_MOCK: Curso[] = [
  {
    id: '1',
    nome: 'Bacharelado em Sistemas de Informação',
    codigo: 'BSI001',
    cargaHoraria: 3200,
    periodos: 8,
    funcionamento: 'Em atividade',
    nivel: 'Graduação',
    turno: 'Noturno',
    modalidade: 'Bacharelado',
    areaConhecimento: 'Ciências Exatas e da Terra',
    grauAcademico: 'Bacharel em Sistemas de Informação',
    conceitoMec: '5',
    coordenador: { id: 'doc-1', nome: 'Dr. Alan Turing' },
    descricao: 'Formação sólida em engenharia de software, banco de dados e gestão de TI.',
  },
  {
    id: '2',
    nome: 'Engenharia de Software',
    codigo: 'ESOFT002',
    cargaHoraria: 3600,
    periodos: 10,
    funcionamento: 'Em atividade',
    nivel: 'Graduação',
    turno: 'Integral',
    modalidade: 'Bacharelado',
    areaConhecimento: 'Ciências Exatas e da Terra',
    grauAcademico: 'Engenheiro de Software',
    conceitoMec: '5',
    coordenador: { id: 'doc-2', nome: 'Dra. Margaret Hamilton' },
    descricao: 'Foco intensivo no ciclo de vida de desenvolvimento, arquitetura e qualidade de software.',
  },
  {
    id: '3',
    nome: 'Ciência da Computação',
    codigo: 'CCO003',
    cargaHoraria: 3400,
    periodos: 8,
    funcionamento: 'Inativo',
    nivel: 'Graduação',
    turno: 'Matutino',
    modalidade: 'Bacharelado',
    areaConhecimento: 'Ciências Exatas e da Terra',
    grauAcademico: 'Bacharel em Computação',
    conceitoMec: '4',
    descricao: 'Fundamentos teóricos de computação, algoritmos avançados e inteligência artificial.',
  },
  {
    id: '4',
    nome: 'Especialização em Arquitetura de Software e Cloud',
    codigo: 'POS-ARC04',
    cargaHoraria: 450,
    periodos: 3,
    funcionamento: 'Em atividade',
    nivel: 'Pós-Graduação',
    turno: 'Noturno',
    modalidade: 'Especialização',
    areaConhecimento: 'Ciências Exatas e da Terra',
    grauAcademico: 'Especialista',
    conceitoMec: '5',
    coordenador: { id: 'doc-3', nome: 'Dr. Martin Fowler' },
    descricao: 'Pós-graduação voltada para profissionais sêniores com foco em microsserviços, AWS e DevOps.',
  },
  {
    id: '5',
    nome: 'Mestrado em Inteligência Artificial',
    codigo: 'MES-IA05',
    cargaHoraria: 1200,
    periodos: 4,
    funcionamento: 'Suspenso',
    nivel: 'Pós-Graduação',
    turno: 'Vespertino',
    modalidade: 'Mestrado Acadêmico',
    areaConhecimento: 'Ciências Exatas e da Terra',
    grauAcademico: 'Mestre em Ciência da Computação',
    descricao: 'Programa stricto sensu dedicado a redes neurais profundas, NLP e visão computacional.',
  },
  {
    id: '6',
    nome: 'ABI - Computação e Informática',
    codigo: 'ABI006',
    cargaHoraria: 2400,
    periodos: 2,
    funcionamento: 'Em atividade',
    nivel: 'Graduação',
    turno: 'Diurno',
    modalidade: 'ABI',
    areaConhecimento: 'Ciências Exatas e da Terra',
    grauAcademico: 'Área Básica de Ingresso',
    conceitoMec: '4',
    descricao: 'Ciclo básico de ingresso comum para escolha posterior entre Computação ou Sistemas.',
  },
];
