/**
 * @file disciplinasGlobalMock.ts
 * @description Mock de dados globais para listagem paginada de todas as disciplinas cadastradas na UFAC.
 */

import type { DisciplinaGlobalItem } from './types';

export const disciplinasGlobalMock: DisciplinaGlobalItem[] = [
  {
    id: 'g1',
    codigo: 'BSI101',
    nome: 'Introdução à Ciência da Computação',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Conceitos fundamentais de computação, arquitetura de computadores básica e evolução histórica tecnológica.',
    objetivos: 'Apresentar aos discentes o universo do processamento de dados e os fundamentos do hardware e software.',
    bibliografiaBasica: 'CAPRON, H. L.; JOHNSON, J. A. Introdução à Informática. 8. ed. Pearson, 2004.',
  },
  {
    id: 'g2',
    codigo: 'BSI102',
    nome: 'Algoritmos e Estrutura de Dados I',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 90,
    creditos: 6,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Desenvolvimento de algoritmos estruturados. Tipos de dados abstratos, vetores, matrizes, registros e manipulação de arquivos.',
    objetivos: 'Capacitar o aluno a construir soluções algorítmicas robustas e modularizadas.',
    bibliografiaBasica: 'ASCENCIO, A. F. G.; CAMPOS, E. A. V. Fundamentos da Programação de Computadores. 3. ed. Pearson, 2012.',
  },
  {
    id: 'g3',
    codigo: 'MAT101',
    nome: 'Cálculo Diferencial e Integral I',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Matutino',
    status: 'Em atividade',
    cargaHoraria: 90,
    creditos: 6,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Limites e continuidade. Derivadas e suas aplicações geométricas e físicas. Integral indefinida e definida.',
    objetivos: 'Fornecer o ferramental matemático analítico básico para engenharias e ciências computacionais.',
    bibliografiaBasica: 'STEWART, James. Cálculo, Volume 1. 7. ed. Cengage Learning, 2013.',
  },
  {
    id: 'g4',
    codigo: 'DIR201',
    nome: 'Direito Constitucional I',
    area: 'Ciências Jurídicas e Sociais',
    nivel: 'Graduação',
    turno: 'Noturno',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 7.0,
    unidade: 'Centro de Ciências Jurídicas e Sociais Aplicadas - CCJSA',
    ementa: 'Teoria geral da constituição. Poder constituinte. Controle de constitucionalidade e direitos fundamentais.',
    objetivos: 'Compreender a supremacia da Constituição e a estrutura jurídico-política do Estado brasileiro.',
    bibliografiaBasica: 'SILVA, José Afonso da. Curso de Direito Constitucional Positivo. 38. ed. Malheiros, 2015.',
  },
  {
    id: 'g5',
    codigo: 'MED301',
    nome: 'Anatomia Humana Geral',
    area: 'Ciências da Saúde e Biológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 120,
    creditos: 8,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências da Saúde e do Esporte - CCSE',
    ementa: 'Estudo macroscópico dos sistemas orgânicos humanos: ósseo, muscular, articular, circulatório e nervoso.',
    objetivos: 'Identificar as estruturas morfológicas normais do corpo humano.',
    bibliografiaBasica: 'DANGELO, J. G.; FATTINI, C. A. Anatomia Humana: Básica e Sistêmica. 3. ed. Atheneu, 2007.',
  },
  {
    id: 'g6',
    codigo: 'AGR105',
    nome: 'Edafologia e Fertilidade do Solo',
    area: 'Ciências Agrárias',
    nivel: 'Graduação',
    turno: 'Vespertino',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Biológicas e da Natureza - CCBN',
    ementa: 'Gênese, morfologia e classificação de solos tropicais. Mecanismos de sorção e nutrição vegetal.',
    objetivos: 'Avaliar o potencial produtivo e o manejo adequado da adubação.',
    bibliografiaBasica: 'NOVAIS, R. F. et al. Fertilidade do Solo. SBCS, 2007.',
  },
  {
    id: 'g7',
    codigo: 'POS901',
    nome: 'Metodologia de Pesquisa Avançada',
    area: 'Multidisciplinar',
    nivel: 'Pós-Graduação',
    turno: 'Noturno',
    status: 'Em atividade',
    cargaHoraria: 45,
    creditos: 3,
    notaMinimaAprovacao: 7.0,
    unidade: 'Pró-Reitoria de Pesquisa e Pós-Graduação',
    ementa: 'Epistemologia da ciência. Estruturação de projetos de dissertação e tese. Ética na pesquisa científica.',
    objetivos: 'Instrumentalizar o pós-graduando na redação científica de alto impacto.',
    bibliografiaBasica: 'CRESWELL, J. W. Projeto de Pesquisa. 3. ed. Artmed, 2010.',
  },
  {
    id: 'g8',
    codigo: 'ENG404',
    nome: 'Resistência dos Materiais I',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Matutino',
    status: 'Suspenso',
    cargaHoraria: 75,
    creditos: 5,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Tensão e deformação. Torção, flexão pura e cisalhamento em vigas.',
    objetivos: 'Calcular esforços internos e dimensionar elementos estruturais sob cargas estáticas.',
    bibliografiaBasica: 'BEER, F. P.; JOHNSTON, E. R. Resistência dos Materiais. 4. ed. Makron Books, 2008.',
  },
  {
    id: 'g9',
    codigo: 'LET102',
    nome: 'Linguística Geral I',
    area: 'Ciências Humanas e Letras',
    nivel: 'Graduação',
    turno: 'Diurno',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Educação, Letras e Artes - CELA',
    ementa: 'O signo linguístico em Saussure. Fonética, fonologia, morfologia e sintaxe estrutural.',
    objetivos: 'Analisar o fenômeno da linguagem humana sob a ótica estruturalista.',
    bibliografiaBasica: 'SAUSSURE, Ferdinand de. Curso de Linguística Geral. Cultrix, 2006.',
  },
  {
    id: 'g10',
    codigo: 'BSI204',
    nome: 'Banco de Dados I',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Modelo Entidade-Relacionamento. Álgebra Relacional. Linguagem SQL avançada (DDL, DML, DQL). Normalização.',
    objetivos: 'Projetar esquemas relacionais eficientes e otimizados.',
    bibliografiaBasica: 'ELMASRI, R.; NAVATHE, S. B. Sistemas de Banco de Dados. 6. ed. Pearson, 2011.',
  },
  {
    id: 'g11',
    codigo: 'ECO101',
    nome: 'Introdução à Economia',
    area: 'Ciências Jurídicas e Sociais',
    nivel: 'Graduação',
    turno: 'Noturno',
    status: 'Inativo',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Jurídicas e Sociais Aplicadas - CCJSA',
    ementa: 'Microeconomia básica: oferta e demanda. Macroeconomia: agregados nacionais, inflação e câmbio.',
    objetivos: 'Compreender o funcionamento dos mercados e o impacto das políticas públicas fiscais.',
    bibliografiaBasica: 'MANKIW, N. Gregory. Introdução à Economia. 6. ed. Cengage, 2013.',
  },
  {
    id: 'g12',
    codigo: 'POS905',
    nome: 'Inteligência Artificial Aplicada',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Pós-Graduação',
    turno: 'Vespertino',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 7.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Redes Neurais Profundas, Transformers, Aprendizado por Reforço e Agentes Autônomos.',
    objetivos: 'Construir modelos preditivos e generativos de alta precisão.',
    bibliografiaBasica: 'RUSSELL, S.; NORVIG, P. Inteligência Artificial: Uma Abordagem Moderna. 3. ed. Campus, 2013.',
  },
  {
    id: 'g13',
    codigo: 'FIL101',
    nome: 'Introdução à Filosofia',
    area: 'Ciências Humanas e Letras',
    nivel: 'Graduação',
    turno: 'Matutino',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Educação, Letras e Artes - CELA',
    ementa: 'Mito e logos. A filosofia pré-socrática. Sócratas, Platão e Aristóteles.',
    objetivos: 'Refletir criticamente sobre os fundamentos do pensamento ocidental.',
    bibliografiaBasica: 'CHAUÍ, Marilena. Convite à Filosofia. Ática, 2000.',
  },
  {
    id: 'g14',
    codigo: 'BSI301',
    nome: 'Engenharia de Software I',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Ciclo de vida do software. Métodos ágeis (Scrum, Kanban). Levantamento de requisitos e Engenharia de Requisitos.',
    objetivos: 'Aplicar processos sistemáticos e controlados no desenvolvimento de sistemas complexos.',
    bibliografiaBasica: 'SOMMERVILLE, Ian. Engenharia de Software. 9. ed. Pearson, 2011.',
  },
  {
    id: 'g15',
    codigo: 'ENF202',
    nome: 'Saúde Coletiva e Epidemiologia',
    area: 'Ciências da Saúde e Biológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 75,
    creditos: 5,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências da Saúde e do Esporte - CCSE',
    ementa: 'Indicadores de saúde. Determinantes sociais da doença. Vigilância em saúde e SUS.',
    objetivos: 'Analisar o perfil epidemiológico populacional para propor ações de prevenção.',
    bibliografiaBasica: 'ROUQUAYROL, M. Z.; ALMEIDA FILHO, N. Epidemiologia & Saúde. 6. ed. Medsi, 2003.',
  },
  {
    id: 'g16',
    codigo: 'PED101',
    nome: 'Psicologia da Educação',
    area: 'Ciências Humanas e Letras',
    nivel: 'Graduação',
    turno: 'Noturno',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Educação, Letras e Artes - CELA',
    ementa: 'Teorias do desenvolvimento humano e aprendizagem: Piaget, Vygotsky, Wallon e Skinner.',
    objetivos: 'Identificar fatores psicológicos que influenciam o processo de ensino-aprendizagem.',
    bibliografiaBasica: 'COLL, C. et al. Desenvolvimento Psicológico e Educação. Artmed, 2004.',
  },
  {
    id: 'g17',
    codigo: 'BSI305',
    nome: 'Redes de Computadores I',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Arquitetura TCP/IP e modelo OSI. Camada de Aplicação (HTTP, DNS) e Transporte (TCP, UDP).',
    objetivos: 'Compreender os protocolos e mecanismos de comunicação de dados em redes mundiais.',
    bibliografiaBasica: 'KUROSE, J. F.; ROSS, K. W. Redes de Computadores e a Internet. 6. ed. Pearson, 2013.',
  },
  {
    id: 'g18',
    codigo: 'CIV501',
    nome: 'Hidráulica e Saneamento Básico',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Matutino',
    status: 'Em atividade',
    cargaHoraria: 90,
    creditos: 6,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Escoamento sob pressão em condutos forçados. Redes de abastecimento de água e coleta de esgoto.',
    objetivos: 'Dimensionar sistemas de adução e distribuição hídrica urbana.',
    bibliografiaBasica: 'PORTO, R. M. Hidráulica Básica. 4. ed. EESC-USP, 2006.',
  },
  {
    id: 'g19',
    codigo: 'POS910',
    nome: 'Ciência de Dados em Saúde Pública',
    area: 'Ciências da Saúde e Biológicas',
    nivel: 'Pós-Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 7.0,
    unidade: 'Centro de Ciências da Saúde e do Esporte - CCSE',
    ementa: 'Análise de grandes bases de dados hospitalares (SIH, SIM). Mineração de texto clínico.',
    objetivos: 'Extrair insights acionáveis para tomadores de decisão em saúde pública amazônica.',
    bibliografiaBasica: 'HASTIE, T. et al. The Elements of Statistical Learning. Springer, 2009.',
  },
  {
    id: 'g20',
    codigo: 'ADM104',
    nome: 'Teoria Geral da Administração',
    area: 'Ciências Jurídicas e Sociais',
    nivel: 'Graduação',
    turno: 'Vespertino',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Jurídicas e Sociais Aplicadas - CCJSA',
    ementa: 'Administração Científica, Teoria Clássica, Relações Humanas, Burocracia e Abordagem Sistêmica.',
    objetivos: 'Analisar a evolução histórica das organizações e modelos de gestão.',
    bibliografiaBasica: 'CHIAVENATO, Idalberto. Introdução à Teoria Geral da Administração. 8. ed. Campus, 2011.',
  },
  {
    id: 'g21',
    codigo: 'FIS101',
    nome: 'Física Geral I (Mecânica)',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 90,
    creditos: 6,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Cinemática vetorial. Leis de Newton. Trabalho e energia cinética. Conservação do momento linear.',
    objetivos: 'Compreender os fenômenos mecânicos clássicos aplicados à engenharia.',
    bibliografiaBasica: 'HALLIDAY, D.; RESNICK, R.; WALKER, J. Fundamentos de Física, Vol 1. 9. ed. LTC, 2012.',
  },
  {
    id: 'g22',
    codigo: 'QUI101',
    nome: 'Química Geral e Inorgânica',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Diurno',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Biológicas e da Natureza - CCBN',
    ementa: 'Estrutura atômica e periodicidade. Ligações químicas. Estequiometria e soluções.',
    objetivos: 'Dominar os equilíbrios e reações estequiométricas fundamentais.',
    bibliografiaBasica: 'ATKINS, P.; JONES, L. Princípios de Química. 5. ed. Bookman, 2012.',
  },
  {
    id: 'g23',
    codigo: 'BIO205',
    nome: 'Genética Molecular e Evolução',
    area: 'Ciências da Saúde e Biológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 75,
    creditos: 5,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Biológicas e da Natureza - CCBN',
    ementa: 'Replicação, transcrição e tradução do DNA. Código genético. Mecanismos de especiação neodarwinista.',
    objetivos: 'Compreender as bases bioquímicas da hereditariedade e diversidade biológica.',
    bibliografiaBasica: 'GRIFFITHS, A. J. F. et al. Introdução à Genética. 9. ed. Guanabara Koogan, 2009.',
  },
  {
    id: 'g24',
    codigo: 'JOR101',
    nome: 'Teoria da Comunicação',
    area: 'Ciências Humanas e Letras',
    nivel: 'Graduação',
    turno: 'Vespertino',
    status: 'Suspenso',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Educação, Letras e Artes - CELA',
    ementa: 'Escola de Frankfurt, Estudos Culturais britânicos e teorias hipodérmicas.',
    objetivos: 'Problematizar o papel dos meios de comunicação de massa na sociedade contemporânea.',
    bibliografiaBasica: 'WOLF, Mauro. Teorias da Comunicação. Presença, 2003.',
  },
  {
    id: 'g25',
    codigo: 'FLOR301',
    nome: 'Manejo Florestal Sustentável',
    area: 'Ciências Agrárias',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 90,
    creditos: 6,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Biológicas e da Natureza - CCBN',
    ementa: 'Inventário florestal na Amazônia. Técnicas de exploração de impacto reduzido. Certificação florestal.',
    objetivos: 'Harmonizar a extração madeireira e não-madeireira com a conservação da biodiversidade.',
    bibliografiaBasica: 'HIGUCHI, N. et al. Manejo Florestal na Amazônia. INPA, 2004.',
  },
  {
    id: 'g26',
    codigo: 'BSI401',
    nome: 'Segurança da Informação',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Noturno',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Confidencialidade, Integridade e Disponibilidade. Criptografia simétrica e assimétrica. Certificados digitais.',
    objetivos: 'Proteger ativos corporativos e mitigar vulnerabilidades cibernéticas.',
    bibliografiaBasica: 'STALLINGS, W. Criptografia e Segurança de Redes. 4. ed. Pearson, 2008.',
  },
  {
    id: 'g27',
    codigo: 'POS920',
    nome: 'Direito Ambiental Amazônico',
    area: 'Ciências Jurídicas e Sociais',
    nivel: 'Pós-Graduação',
    turno: 'Noturno',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 7.0,
    unidade: 'Centro de Ciências Jurídicas e Sociais Aplicadas - CCJSA',
    ementa: 'Código Florestal. Proteção dos saberes tradicionais. Crimes ambientais na bacia amazônica.',
    objetivos: 'Desenvolver fundamentação crítica na defesa do ecossistema e povos nativos.',
    bibliografiaBasica: 'ANTUNES, P. B. Direito Ambiental. 17. ed. Atlas, 2015.',
  },
  {
    id: 'g28',
    codigo: 'HIS105',
    nome: 'História da Amazônia',
    area: 'Ciências Humanas e Letras',
    nivel: 'Graduação',
    turno: 'Matutino',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Educação, Letras e Artes - CELA',
    ementa: 'A ocupação pré-colombiana. Ciclos da borracha. Tratado de Petrópolis e a formação do Acre.',
    objetivos: 'Conhecer a identidade sócio-histórica acriana e amazônica no contexto nacional.',
    bibliografiaBasica: 'TOCANTINS, Leandro. Formação Histórica do Acre. Civilização Brasileira, 2001.',
  },
  {
    id: 'g29',
    codigo: 'VET201',
    nome: 'Patologia Clínica Veterinária',
    area: 'Ciências Agrárias',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Inativo',
    cargaHoraria: 90,
    creditos: 6,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Biológicas e da Natureza - CCBN',
    ementa: 'Hematologia, parasitologia e urinálise de animais de grande e pequeno porte.',
    objetivos: 'Interpretar exames laboratoriais complementares diagnósticos veterinários.',
    bibliografiaBasica: 'THRALL, M. A. et al. Hematologia e Bioquímica Clínica Veterinária. Roca, 2007.',
  },
  {
    id: 'g30',
    codigo: 'BSI405',
    nome: 'Sistemas Distribuídos',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Comunicação inter-processos (RPC, gRPC). Relógios lógicos de Lamport. Consenso e replicação (Raft, Paxos).',
    objetivos: 'Desenvolver aplicações concorrentes altamente escaláveis e tolerantes a falhas.',
    bibliografiaBasica: 'TANENBAUM, A. S.; VAN STEEN, M. Sistemas Distribuídos: Princípios e Paradigmas. 2. ed. Pearson, 2008.',
  },
  {
    id: 'g31',
    codigo: 'ART101',
    nome: 'Expressão Vocal e Corporal',
    area: 'Ciências Humanas e Letras',
    nivel: 'Graduação',
    turno: 'Diurno',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Educação, Letras e Artes - CELA',
    ementa: 'Consciência corporal no espaço cênico. Respiração diafragmática e ressonância vocal.',
    objetivos: 'Desenvolver a expressividade artística e comunicativa do ator-performer.',
    bibliografiaBasica: 'SPOLIN, Viola. Improvisação para o Teatro. Perspectiva, 2005.',
  },
  {
    id: 'g32',
    codigo: 'GEO204',
    nome: 'Geoprocessamento e Sensoriamento Remoto',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Vespertino',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Sistemas de Informação Geográfica (SIG). Processamento digital de imagens de satélite Landsat e Sentinel.',
    objetivos: 'Mapear fenômenos espaciais e monitorar o desmatamento amazônico.',
    bibliografiaBasica: 'FLORENZANO, T. G. Iniciação em Sensoriamento Remoto. Oficina de Textos, 2007.',
  },
  {
    id: 'g33',
    codigo: 'NUT102',
    nome: 'Bioquímica da Nutrição',
    area: 'Ciências da Saúde e Biológicas',
    nivel: 'Graduação',
    turno: 'Matutino',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências da Saúde e do Esporte - CCSE',
    ementa: 'Metabolismo de carboidratos, lipídios e proteínas. Ciclo de Krebs e fosforilação oxidativa.',
    objetivos: 'Compreender os destinos energéticos e plásticos dos macro e micronutrientes.',
    bibliografiaBasica: 'CHAMPE, P. C.; HARVEY, R. A. Bioquímica Ilustrada. 4. ed. Artmed, 2009.',
  },
  {
    id: 'g34',
    codigo: 'POS930',
    nome: 'Biotecnologia Vegetal Tropical',
    area: 'Ciências Agrárias',
    nivel: 'Pós-Graduação',
    turno: 'Integral',
    status: 'Em atividade',
    cargaHoraria: 60,
    creditos: 4,
    notaMinimaAprovacao: 7.0,
    unidade: 'Centro de Ciências Biológicas e da Natureza - CCBN',
    ementa: 'Cultura de tecidos *in vitro*. Marcadores moleculares e melhoramento genético vegetal amazônico.',
    objetivos: 'Conservar germoplasmas raros e propagar cultivares resistentes a pragas regionais.',
    bibliografiaBasica: 'TORRES, A. C. et al. Cultura de Tecidos e Transformação Genética de Plantas. EMBRAPA, 1999.',
  },
  {
    id: 'g35',
    codigo: 'BSI410',
    nome: 'Trabalho de Conclusão de Curso I',
    area: 'Ciências Exactas e Tecnológicas',
    nivel: 'Graduação',
    turno: 'Noturno',
    status: 'Em atividade',
    cargaHoraria: 30,
    creditos: 2,
    notaMinimaAprovacao: 5.0,
    unidade: 'Centro de Ciências Exactas e Tecnológicas - CCET',
    ementa: 'Definição do tema de pesquisa. Redação da fundamentação teórica e cronograma de trabalho.',
    objetivos: 'Elaborar e defender publicamente o projeto de pesquisa do TCC.',
    bibliografiaBasica: 'SEVERINO, A. J. Metodologia do Trabalho Científico. 23. ed. Cortez, 2007.',
  },
];
